"""
User Management REST API
Generated by Code Alpha Kiro
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, EmailStr
from typing import List, Optional
import uuid

app = FastAPI(title="User Management API", version="1.0.0")

# ── Data model ─────────────────────────────────────────────────────────────
class UserCreate(BaseModel):
    name: str
    email: str
    role: str = "user"

class User(UserCreate):
    id: str
    created_at: str

# ── In-memory store (replace with DB in production) ─────────────────────────
users: List[User] = [
    User(id="u1", name="Alice",   email="alice@example.com", role="admin",  created_at="2026-01-01"),
    User(id="u2", name="Bob",     email="bob@example.com",   role="user",   created_at="2026-01-02"),
]

# ── Endpoints ────────────────────────────────────────────────────────────────
@app.get("/users", response_model=List[User], summary="List all users")
async def list_users():
    return users

@app.get("/users/{user_id}", response_model=User, summary="Get single user")
async def get_user(user_id: str):
    user = next((u for u in users if u.id == user_id), None)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user

@app.post("/users", response_model=User, status_code=201, summary="Create user")
async def create_user(payload: UserCreate):
    new_user = User(
        id=str(uuid.uuid4())[:8],
        created_at=__import__("datetime").date.today().isoformat(),
        **payload.dict(),
    )
    users.append(new_user)
    return new_user

@app.put("/users/{user_id}", response_model=User, summary="Update user")
async def update_user(user_id: str, payload: UserCreate):
    for i, u in enumerate(users):
        if u.id == user_id:
            users[i] = User(id=user_id, created_at=u.created_at, **payload.dict())
            return users[i]
    raise HTTPException(status_code=404, detail="User not found")

@app.delete("/users/{user_id}", summary="Delete user")
async def delete_user(user_id: str):
    global users
    if not any(u.id == user_id for u in users):
        raise HTTPException(status_code=404, detail="User not found")
    users = [u for u in users if u.id != user_id]
    return {"message": f"User {user_id} deleted"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
