"""
Fibonacci Implementations — three flavours
Generated by Code Alpha Kiro
"""
from functools import lru_cache
from typing import Iterator


# ── 1. Simple iterative (fastest for single call) ────────────────────────────
def fibonacci(n: int) -> list[int]:
    """Return the first *n* Fibonacci numbers as a list."""
    if n <= 0:
        return []
    if n == 1:
        return [0]
    seq = [0, 1]
    while len(seq) < n:
        seq.append(seq[-1] + seq[-2])
    return seq


# ── 2. Memoised recursive (clean for repeated single-value lookups) ──────────
@lru_cache(maxsize=None)
def fib(n: int) -> int:
    """Return the n-th Fibonacci number (0-indexed)."""
    if n < 0:
        raise ValueError("n must be >= 0")
    if n in (0, 1):
        return n
    return fib(n - 1) + fib(n - 2)


# ── 3. Generator (memory-efficient for very large sequences) ─────────────────
def fib_gen(limit: int) -> Iterator[int]:
    """Yield Fibonacci numbers up to (but not including) *limit*."""
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a + b


# ── Demo ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("First 10 :", fibonacci(10))
    print("fib(20)  :", fib(20))
    print("Under 100:", list(fib_gen(100)))
