"""
app.py
------
Streamlit demo: Chat tab (talk to the agent) + Admin tab (enable/
disable plugins, see what's discovered, rescan). Because the registry
re-scans the plugins/ folder and re-reads the state file on every
single agent call, toggling a plugin in the Admin tab takes effect on
your very next chat message -- no restart needed.

Run with:
    streamlit run app.py
"""

import streamlit as st

from core.agent import PluginAgent, AgentInitError, AgentRequestError
from core.registry import PluginRegistry

st.set_page_config(page_title="Plugin Tool System", page_icon="\U0001F50C", layout="wide")
st.title("\U0001F50C Dynamic Plugin Tool System")
st.caption("Add, enable, or disable tools without touching the agent's code -- like a mini plugin store.")

registry = PluginRegistry()

if "agent" not in st.session_state:
    try:
        st.session_state.agent = PluginAgent(registry=registry)
        st.session_state.agent_error = None
    except AgentInitError as exc:
        st.session_state.agent = None
        st.session_state.agent_error = str(exc)

if "chat_log" not in st.session_state:
    st.session_state.chat_log = []

tab_chat, tab_admin = st.tabs(["\U0001F4AC Chat", "\U0001F6E0\uFE0F Admin — Manage Plugins"])

# --------------------------------------------------------------------------
# Chat tab
# --------------------------------------------------------------------------
with tab_chat:
    if st.session_state.agent_error:
        st.error(st.session_state.agent_error)
    else:
        for role, text in st.session_state.chat_log:
            with st.chat_message(role):
                st.write(text)

        user_input = st.chat_input("Ask something (try: 'Convert 10 km to miles')")
        if user_input:
            st.session_state.chat_log.append(("user", user_input))
            with st.chat_message("user"):
                st.write(user_input)

            with st.chat_message("assistant"):
                with st.spinner("Thinking..."):
                    try:
                        answer = st.session_state.agent.ask(user_input)
                    except AgentRequestError as exc:
                        answer = str(exc)
                st.write(answer)
            st.session_state.chat_log.append(("assistant", answer))

        if st.button("Clear conversation"):
            st.session_state.chat_log = []
            if st.session_state.agent:
                st.session_state.agent.reset()
            st.rerun()

# --------------------------------------------------------------------------
# Admin tab
# --------------------------------------------------------------------------
with tab_admin:
    st.subheader("Discovered plugins")
    st.write(
        "This list is generated by scanning the `plugins/` folder fresh, right now. "
        "Drop a new `*_plugin.py` file in there and click **Rescan** to see it appear "
        "here -- no restart needed."
    )

    if st.button("\U0001F504 Rescan plugins folder"):
        st.rerun()

    plugins_status = registry.list_all_with_status()

    if not plugins_status:
        st.warning("No plugins found in the plugins/ folder.")
    else:
        for plugin in plugins_status:
            col1, col2, col3 = st.columns([2, 5, 2])
            with col1:
                st.markdown(f"**{plugin['name']}**")
            with col2:
                st.write(plugin["description"])
            with col3:
                new_state = st.toggle(
                    "Enabled", value=plugin["enabled"], key=f"toggle_{plugin['name']}"
                )
                if new_state != plugin["enabled"]:
                    registry.set_enabled(plugin["name"], new_state)
                    st.rerun()

    st.divider()
    st.caption(
        "Tools currently exposed to the agent (i.e. what the LLM sees in its "
        "function-calling schema right now):"
    )
    enabled_names = list(registry.get_enabled_plugins().keys())
    st.code(", ".join(enabled_names) if enabled_names else "(none enabled)")
