from .style import StyleProfile

LICENSE_HEADER = "# Copyright (c) {year} — generated by Code Alpha\n"


def generate_boilerplate(
    file_path: str,
    purpose: str,
    style: StyleProfile,
    imports: list[str] | None = None,
    year: int = 2026,
) -> str:
    """Boilerplate for a brand-new file: license header, a one-line purpose
    docstring/comment, and an import block ordered/spaced per the detected
    project style."""
    imports = imports or []

    if file_path.endswith(".py"):
        parts = [LICENSE_HEADER.format(year=year), f'"""{purpose}"""\n']
        if imports:
            if style.import_style == "grouped":
                stdlib = [i for i in imports if i.startswith("import ") and "." not in i]
                rest = [i for i in imports if i not in stdlib]
                block = "\n".join(stdlib) + ("\n\n" if stdlib and rest else "") + "\n".join(rest)
            else:
                block = "\n".join(imports)
            parts.append(block + "\n")
        return "\n".join(parts) + "\n"

    # generic comment-style header for non-Python files
    parts = [f"// {purpose}\n"] + imports
    return "\n".join(parts) + "\n"
