"""
Command-line interface for the image captioning tool.

Usage:
    python cli.py

Prompts for a path to an image file (your photo, an object, etc.) and
prints a short, descriptive caption generated by a vision-enabled LLM.
Type 'exit' to quit.
"""

from captioner import get_client, caption_image, CaptionError


def main():
    client = get_client()
    print("=" * 55)
    print("  Image Captioning Tool")
    print("=" * 55)
    print("Enter the path to an image file (jpg, png, webp, gif).")
    print("Type 'exit' to quit.\n")

    while True:
        image_path = input("Image path: ").strip().strip('"')

        if image_path.lower() == "exit":
            print("Goodbye!")
            break
        if not image_path:
            print("Please enter a file path.\n")
            continue

        try:
            caption = caption_image(client, image_path)
            print(f"\nCaption: {caption}\n")
        except CaptionError as e:
            print(f"\n[Error] {e}\n")


if __name__ == "__main__":
    main()
