(()=>{const s=document.currentScript,id=s?.dataset.botId||"tenant-a",api=new URL(s.src).origin;
class AIChatWidget extends HTMLElement{constructor(){super();this.attachShadow({mode:"open"});this.history=[];this.config=null}
connectedCallback(){this.render();this.load()}
render(){this.shadowRoot.innerHTML=`<style>
*{box-sizing:border-box}.wrap{position:fixed;right:22px;bottom:22px;z-index:2147483647;font-family:Arial,sans-serif}
.bubble{width:60px;height:60px;border:0;border-radius:50%;color:#fff;background:#2563eb;cursor:pointer;box-shadow:0 10px 28px #0003;font-size:25px}
.panel{position:absolute;right:0;bottom:72px;width:360px;height:520px;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 18px 55px #0004;display:flex;flex-direction:column;opacity:0;transform:translateY(14px) scale(.97);pointer-events:none;transition:.2s}
.panel.open{opacity:1;transform:none;pointer-events:auto}.header{color:#fff;padding:14px;display:flex;align-items:center;gap:10px}.logo{width:36px;height:36px;border-radius:50%;background:#fff}.title{font-weight:700}.status{font-size:11px;opacity:.85}.close{margin-left:auto;background:none;border:0;color:#fff;font-size:20px}
.messages{flex:1;padding:14px;overflow:auto;background:#f7f8fa}.msg{max-width:85%;padding:10px 12px;margin:7px 0;border-radius:13px;line-height:1.4;font-size:14px;white-space:pre-wrap}.bot{background:#fff;border:1px solid #e6e7eb}.user{margin-left:auto;color:#fff}.composer{display:flex;gap:7px;padding:10px;border-top:1px solid #eee}textarea{flex:1;resize:none;border:1px solid #ddd;border-radius:10px;padding:9px;font:inherit;height:42px}.send{border:0;color:#fff;border-radius:10px;padding:0 14px;cursor:pointer}
@media(max-width:600px){.wrap{right:12px;bottom:12px}.panel{position:fixed;left:10px;right:10px;bottom:82px;width:auto;height:70vh}}
</style><div class="wrap"><section class="panel"><header class="header"><img class="logo"><div><div class="title">AI Assistant</div><div class="status">Online</div></div><button class="close">×</button></header><main class="messages"></main><form class="composer"><textarea placeholder="Type a message..."></textarea><button class="send">Send</button></form></section><button class="bubble">💬</button></div>`;
this.panel=this.shadowRoot.querySelector(".panel");this.messages=this.shadowRoot.querySelector(".messages");this.textarea=this.shadowRoot.querySelector("textarea");this.send=this.shadowRoot.querySelector(".send");
this.shadowRoot.querySelector(".bubble").onclick=()=>this.toggle(true);this.shadowRoot.querySelector(".close").onclick=()=>this.toggle(false);this.shadowRoot.querySelector("form").onsubmit=e=>{e.preventDefault();this.sendMsg()}}
async load(){try{let r=await fetch(`${api}/api/config/${encodeURIComponent(id)}`);this.config=await r.json();this.shadowRoot.querySelector(".title").textContent=this.config.name;this.shadowRoot.querySelector(".logo").src=this.config.logo;this.shadowRoot.querySelector(".header").style.background=this.config.color;this.send.style.background=this.config.color;this.shadowRoot.querySelector(".bubble").style.background=this.config.color;this.add("bot",this.config.welcome)}catch(e){this.add("bot","Unable to load chatbot.")}}
toggle(x){this.panel.classList.toggle("open",x);if(x)this.textarea.focus()}
add(role,text){let d=document.createElement("div");d.className="msg "+role;d.textContent=text;if(role==="user")d.style.background=this.config?.color||"#2563eb";this.messages.appendChild(d);this.messages.scrollTop=this.messages.scrollHeight}
async sendMsg(){let m=this.textarea.value.trim();if(!m)return;this.add("user",m);this.history.push({role:"user",content:m});this.textarea.value="";this.send.disabled=true;
try{let r=await fetch(`${api}/api/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bot_id:id,message:m,history:this.history})});let d=await r.json();if(!r.ok)throw Error();this.add("bot",d.answer);this.history.push({role:"assistant",content:d.answer})}catch(e){this.add("bot","Sorry, something went wrong.")}finally{this.send.disabled=false}}}
customElements.define("ai-tenant-chat",AIChatWidget);document.body.appendChild(document.createElement("ai-tenant-chat"))})()
