"""
Code Alpha Kiro Backend - v4 (Fixed)
- Pattern matching fixed for REST API, HTML, CSS, JS, Python, Tests, etc.
- Sub-tasks execute synchronously so status is correct on every GET poll
- SSE /stream endpoint pushes sub-task updates one by one with real delays
- Files written to workspace root (passed as repo_path)
"""

import asyncio
import json
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

app = FastAPI(title="Code Alpha Kiro", version="4.0.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# ─────────────────────────────────────────────────────────────────────────────
# MODELS
# ─────────────────────────────────────────────────────────────────────────────

class TaskCreate(BaseModel):
    prompt: str
    repo_path: str = "."


class SubTask(BaseModel):
    id: int
    name: str
    status: str   # pending | running | complete | error
    detail: str = ""


class TaskOut(BaseModel):
    task_id: str
    prompt: str
    status: str   # pending | running | complete | error
    pattern: str
    file_ext: str
    file_name: str
    file_path: str
    sub_tasks: List[SubTask]
    generated_code: Optional[str]
    logs: List[str]


# ─────────────────────────────────────────────────────────────────────────────
# PATTERN LIBRARY  (keywords scored, highest wins)
# ─────────────────────────────────────────────────────────────────────────────

PATTERNS: Dict[str, Dict[str, Any]] = {

    "rest_api": {
        "keywords": ["rest api", "rest", "api", "endpoint", "user management",
                     "crud", "routes", "fastapi", "flask", "express"],
        "file_ext": "py",
        "subtasks": [
            "Analysing REST API requirements",
            "Designing data models (User schema)",
            "Creating GET /users endpoint",
            "Creating POST /users endpoint",
            "Creating PUT /users/{id} endpoint",
            "Creating DELETE /users/{id} endpoint",
            "Adding error handling & validation",
            "Writing file to workspace",
        ],
        "code": '''\
"""
User Management REST API
Generated by Code Alpha Kiro
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, EmailStr
from typing import List, Optional
import uuid

app = FastAPI(title="User Management API", version="1.0.0")

# ── Data model ─────────────────────────────────────────────────────────────
class UserCreate(BaseModel):
    name: str
    email: str
    role: str = "user"

class User(UserCreate):
    id: str
    created_at: str

# ── In-memory store (replace with DB in production) ─────────────────────────
users: List[User] = [
    User(id="u1", name="Alice",   email="alice@example.com", role="admin",  created_at="2026-01-01"),
    User(id="u2", name="Bob",     email="bob@example.com",   role="user",   created_at="2026-01-02"),
]

# ── Endpoints ────────────────────────────────────────────────────────────────
@app.get("/users", response_model=List[User], summary="List all users")
async def list_users():
    return users

@app.get("/users/{user_id}", response_model=User, summary="Get single user")
async def get_user(user_id: str):
    user = next((u for u in users if u.id == user_id), None)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user

@app.post("/users", response_model=User, status_code=201, summary="Create user")
async def create_user(payload: UserCreate):
    new_user = User(
        id=str(uuid.uuid4())[:8],
        created_at=__import__("datetime").date.today().isoformat(),
        **payload.dict(),
    )
    users.append(new_user)
    return new_user

@app.put("/users/{user_id}", response_model=User, summary="Update user")
async def update_user(user_id: str, payload: UserCreate):
    for i, u in enumerate(users):
        if u.id == user_id:
            users[i] = User(id=user_id, created_at=u.created_at, **payload.dict())
            return users[i]
    raise HTTPException(status_code=404, detail="User not found")

@app.delete("/users/{user_id}", summary="Delete user")
async def delete_user(user_id: str):
    global users
    if not any(u.id == user_id for u in users):
        raise HTTPException(status_code=404, detail="User not found")
    users = [u for u in users if u.id != user_id]
    return {"message": f"User {user_id} deleted"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8001)
''',
    },

    "html_page": {
        "keywords": ["html", "web page", "webpage", "website", "landing page",
                     "front end", "frontend", "browser"],
        "file_ext": "html",
        "subtasks": [
            "Analysing HTML page requirements",
            "Designing page layout & sections",
            "Writing semantic HTML structure",
            "Adding CSS styling (colours, fonts, layout)",
            "Making layout responsive (mobile-first)",
            "Adding JavaScript interactions",
            "Writing file to workspace",
        ],
        "code": '''\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Modern Web Page</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    :root {
      --primary: #6366f1;
      --primary-dark: #4f46e5;
      --bg: #0f172a;
      --surface: #1e293b;
      --text: #e2e8f0;
      --muted: #94a3b8;
    }

    body { background: var(--bg); color: var(--text); font-family: 'Segoe UI', sans-serif; line-height: 1.6; }

    /* ── Nav ── */
    nav {
      display: flex; justify-content: space-between; align-items: center;
      padding: 1rem 2rem; background: var(--surface);
      border-bottom: 1px solid rgba(255,255,255,.08);
    }
    nav .logo { font-size: 1.4rem; font-weight: 700; color: var(--primary); }
    nav ul { list-style: none; display: flex; gap: 1.5rem; }
    nav a { color: var(--muted); text-decoration: none; transition: color .2s; }
    nav a:hover { color: var(--text); }

    /* ── Hero ── */
    .hero {
      text-align: center; padding: 6rem 2rem;
      background: radial-gradient(ellipse at top, #312e81 0%, var(--bg) 70%);
    }
    .hero h1 { font-size: clamp(2rem, 5vw, 3.5rem); margin-bottom: 1rem; }
    .hero h1 span { color: var(--primary); }
    .hero p { color: var(--muted); max-width: 600px; margin: 0 auto 2rem; font-size: 1.1rem; }
    .btn {
      display: inline-block; padding: .8rem 2rem;
      background: var(--primary); color: #fff; border-radius: 8px;
      text-decoration: none; font-weight: 600; transition: background .2s;
    }
    .btn:hover { background: var(--primary-dark); }

    /* ── Features ── */
    .features { padding: 4rem 2rem; max-width: 1100px; margin: 0 auto; }
    .features h2 { text-align: center; font-size: 2rem; margin-bottom: 2.5rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 1.5rem; }
    .card {
      background: var(--surface); padding: 1.8rem; border-radius: 12px;
      border: 1px solid rgba(255,255,255,.06); transition: transform .2s;
    }
    .card:hover { transform: translateY(-4px); }
    .card .icon { font-size: 2rem; margin-bottom: .8rem; }
    .card h3 { margin-bottom: .5rem; }
    .card p { color: var(--muted); font-size: .9rem; }

    /* ── Footer ── */
    footer {
      text-align: center; padding: 2rem; color: var(--muted);
      border-top: 1px solid rgba(255,255,255,.06);
    }

    @media (max-width: 640px) {
      nav ul { display: none; }
      .hero { padding: 4rem 1rem; }
    }
  </style>
</head>
<body>

  <nav>
    <div class="logo">⚡ MyApp</div>
    <ul>
      <li><a href="#features">Features</a></li>
      <li><a href="#about">About</a></li>
      <li><a href="#contact">Contact</a></li>
    </ul>
    <a href="#" class="btn">Get Started</a>
  </nav>

  <section class="hero">
    <h1>Build <span>Faster</span> with Modern Tools</h1>
    <p>A clean, responsive landing page with dark theme, smooth animations, and mobile support — generated by Code Alpha Kiro.</p>
    <a href="#features" class="btn">Explore Features</a>
  </section>

  <section class="features" id="features">
    <h2>Why Choose Us?</h2>
    <div class="grid">
      <div class="card">
        <div class="icon">🚀</div>
        <h3>Lightning Fast</h3>
        <p>Optimised for performance with minimal CSS and semantic HTML.</p>
      </div>
      <div class="card">
        <div class="icon">📱</div>
        <h3>Responsive</h3>
        <p>Looks great on every device — desktop, tablet, and mobile.</p>
      </div>
      <div class="card">
        <div class="icon">🎨</div>
        <h3>Dark Theme</h3>
        <p>Professional dark UI with CSS custom properties for easy theming.</p>
      </div>
      <div class="card">
        <div class="icon">♿</div>
        <h3>Accessible</h3>
        <p>Semantic markup and sufficient colour contrast for all users.</p>
      </div>
    </div>
  </section>

  <footer>
    <p>&copy; 2026 MyApp — Generated by <strong>Code Alpha Kiro</strong></p>
  </footer>

  <script>
    // Smooth scroll for anchor links
    document.querySelectorAll('a[href^="#"]').forEach(a => {
      a.addEventListener('click', e => {
        e.preventDefault();
        document.querySelector(a.getAttribute('href'))?.scrollIntoView({ behavior: 'smooth' });
      });
    });
  </script>
</body>
</html>
''',
    },

    "css_stylesheet": {
        "keywords": ["css", "stylesheet", "style", "design", "theme", "tailwind"],
        "file_ext": "css",
        "subtasks": [
            "Analysing CSS requirements",
            "Setting CSS custom properties (variables)",
            "Writing reset & base styles",
            "Building typography system",
            "Creating layout utilities (flex, grid)",
            "Adding component styles (buttons, cards, forms)",
            "Adding responsive media queries",
            "Writing file to workspace",
        ],
        "code": '''\
/* ============================================================
   Design System Stylesheet — Code Alpha Kiro
   ============================================================ */

/* ── Variables ─────────────────────────────────────────────── */
:root {
  --clr-primary:     #6366f1;
  --clr-primary-dk:  #4f46e5;
  --clr-success:     #10b981;
  --clr-danger:      #ef4444;
  --clr-warning:     #f59e0b;

  --clr-bg:          #0f172a;
  --clr-surface:     #1e293b;
  --clr-border:      rgba(255, 255, 255, 0.08);
  --clr-text:        #e2e8f0;
  --clr-muted:       #94a3b8;

  --radius-sm:  4px;
  --radius-md:  8px;
  --radius-lg:  16px;

  --shadow-sm:  0 1px 3px rgba(0,0,0,.4);
  --shadow-md:  0 4px 12px rgba(0,0,0,.5);

  --font-base:  'Segoe UI', system-ui, sans-serif;
  --font-mono:  'Cascadia Code', 'Fira Code', monospace;
}

/* ── Reset ──────────────────────────────────────────────────── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body { font-family: var(--font-base); background: var(--clr-bg); color: var(--clr-text); line-height: 1.6; }
img, video { max-width: 100%; display: block; }

/* ── Typography ─────────────────────────────────────────────── */
h1 { font-size: clamp(2rem,   5vw, 3rem);   font-weight: 800; }
h2 { font-size: clamp(1.5rem, 4vw, 2.2rem); font-weight: 700; }
h3 { font-size: 1.25rem; font-weight: 600; }
p  { color: var(--clr-muted); margin-bottom: 1rem; }
a  { color: var(--clr-primary); text-decoration: none; }
a:hover { text-decoration: underline; }
code { font-family: var(--font-mono); font-size: .875em; background: var(--clr-surface); padding: .15em .4em; border-radius: var(--radius-sm); }

/* ── Layout ─────────────────────────────────────────────────── */
.container  { max-width: 1200px; margin: 0 auto; padding: 0 1.5rem; }
.flex       { display: flex; }
.flex-center{ display: flex; align-items: center; justify-content: center; }
.grid       { display: grid; }
.grid-2     { grid-template-columns: repeat(2, 1fr); gap: 1.5rem; }
.grid-3     { grid-template-columns: repeat(3, 1fr); gap: 1.5rem; }
.grid-auto  { grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; }

/* ── Buttons ────────────────────────────────────────────────── */
.btn {
  display: inline-flex; align-items: center; gap: .4rem;
  padding: .6rem 1.4rem; border-radius: var(--radius-md);
  font-weight: 600; font-size: .95rem; cursor: pointer;
  border: none; transition: background .2s, transform .1s;
}
.btn:active { transform: scale(.97); }
.btn-primary  { background: var(--clr-primary);  color: #fff; }
.btn-primary:hover  { background: var(--clr-primary-dk); }
.btn-success  { background: var(--clr-success);  color: #fff; }
.btn-danger   { background: var(--clr-danger);   color: #fff; }
.btn-outline  { background: transparent; border: 2px solid var(--clr-primary); color: var(--clr-primary); }
.btn-sm { padding: .35rem .9rem; font-size: .85rem; }
.btn-lg { padding: .9rem 2rem;   font-size: 1.1rem; }

/* ── Cards ──────────────────────────────────────────────────── */
.card {
  background: var(--clr-surface);
  border: 1px solid var(--clr-border);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  box-shadow: var(--shadow-sm);
  transition: box-shadow .2s, transform .2s;
}
.card:hover { box-shadow: var(--shadow-md); transform: translateY(-3px); }
.card-header { font-weight: 700; margin-bottom: .75rem; font-size: 1.1rem; }

/* ── Forms ──────────────────────────────────────────────────── */
.form-group { margin-bottom: 1.2rem; }
label { display: block; margin-bottom: .35rem; font-size: .9rem; color: var(--clr-muted); }
input, textarea, select {
  width: 100%; padding: .65rem .9rem;
  background: var(--clr-surface); color: var(--clr-text);
  border: 1px solid var(--clr-border); border-radius: var(--radius-md);
  font-family: inherit; font-size: 1rem; transition: border-color .2s;
}
input:focus, textarea:focus, select:focus { outline: none; border-color: var(--clr-primary); }

/* ── Badges ─────────────────────────────────────────────────── */
.badge { display: inline-block; padding: .2rem .7rem; border-radius: 999px; font-size: .75rem; font-weight: 700; }
.badge-primary { background: rgba(99,102,241,.2); color: var(--clr-primary); }
.badge-success { background: rgba(16,185,129,.2); color: var(--clr-success); }
.badge-danger  { background: rgba(239, 68, 68,.2); color: var(--clr-danger);  }

/* ── Responsive ─────────────────────────────────────────────── */
@media (max-width: 768px) {
  .grid-2, .grid-3 { grid-template-columns: 1fr; }
  .hide-mobile { display: none; }
}
@media (max-width: 480px) {
  .container { padding: 0 1rem; }
}
''',
    },

    "javascript": {
        "keywords": ["javascript", "js", "node", "script", "interactive",
                     "dom", "event", "frontend js", "vanilla js"],
        "file_ext": "js",
        "subtasks": [
            "Analysing JavaScript requirements",
            "Defining module structure",
            "Implementing core class & constructor",
            "Adding data-fetching / storage methods",
            "Building DOM manipulation helpers",
            "Attaching event listeners",
            "Adding error handling & exports",
            "Writing file to workspace",
        ],
        "code": '''\
/**
 * Interactive Web Application Module
 * Generated by Code Alpha Kiro
 */

class App {
  constructor(options = {}) {
    this.apiBase   = options.apiBase || '/api';
    this.container = options.container || document.getElementById('app');
    this.state     = { items: [], loading: false, error: null };
    this._init();
  }

  // ── Lifecycle ───────────────────────────────────────────────────────────
  _init() {
    this._render();
    this._attachEvents();
    this.fetchItems();
  }

  // ── State management ────────────────────────────────────────────────────
  setState(patch) {
    this.state = { ...this.state, ...patch };
    this._render();
  }

  // ── Network ─────────────────────────────────────────────────────────────
  async fetchItems() {
    this.setState({ loading: true, error: null });
    try {
      const res  = await fetch(`${this.apiBase}/items`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      this.setState({ items: data, loading: false });
    } catch (err) {
      this.setState({ error: err.message, loading: false });
    }
  }

  async createItem(payload) {
    const res = await fetch(`${this.apiBase}/items`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error('Failed to create item');
    const item = await res.json();
    this.setState({ items: [...this.state.items, item] });
    return item;
  }

  async deleteItem(id) {
    await fetch(`${this.apiBase}/items/${id}`, { method: 'DELETE' });
    this.setState({ items: this.state.items.filter(i => i.id !== id) });
  }

  // ── Rendering ───────────────────────────────────────────────────────────
  _render() {
    if (!this.container) return;
    const { items, loading, error } = this.state;

    if (loading) { this.container.innerHTML = '<p class="loading">Loading…</p>'; return; }
    if (error)   { this.container.innerHTML = `<p class="error">Error: ${error}</p>`; return; }

    this.container.innerHTML = `
      <div class="item-list">
        ${items.map(item => this._renderItem(item)).join('')}
      </div>
      <form class="add-form" id="add-form">
        <input name="title" placeholder="Add item…" required />
        <button type="submit">Add</button>
      </form>
    `;

    // Re-attach after re-render
    this._attachEvents();
  }

  _renderItem(item) {
    return `
      <div class="item" data-id="${item.id}">
        <span>${this._escape(item.title)}</span>
        <button class="delete-btn" data-id="${item.id}">✕</button>
      </div>
    `;
  }

  // ── Events ───────────────────────────────────────────────────────────────
  _attachEvents() {
    this.container?.querySelectorAll('.delete-btn').forEach(btn => {
      btn.addEventListener('click', () => this.deleteItem(btn.dataset.id));
    });

    const form = this.container?.querySelector('#add-form');
    form?.addEventListener('submit', async e => {
      e.preventDefault();
      const title = new FormData(form).get('title');
      await this.createItem({ title });
      form.reset();
    });
  }

  // ── Utilities ───────────────────────────────────────────────────────────
  _escape(str) {
    return String(str).replace(/[<>&"']/g, c =>
      ({ '<':'&lt;', '>':'&gt;', '&':'&amp;', '"':'&quot;', "'":'&#39;' }[c])
    );
  }
}

// Bootstrap when DOM is ready
if (typeof window !== 'undefined') {
  document.addEventListener('DOMContentLoaded', () => {
    window.app = new App();
  });
}

// Allow Node.js import
if (typeof module !== 'undefined') module.exports = App;
''',
    },

    "unit_tests": {
        "keywords": ["test", "tests", "unit test", "pytest", "unittest", "testing"],
        "file_ext": "py",
        "subtasks": [
            "Analysing testing requirements",
            "Designing test fixtures & setUp",
            "Writing Calculator class to test",
            "Writing arithmetic tests (add, sub, mul, div)",
            "Writing edge-case tests (zero, negative, float)",
            "Writing error / exception tests",
            "Adding test runner entry point",
            "Writing file to workspace",
        ],
        "code": '''\
"""
Unit Test Suite — Calculator
Generated by Code Alpha Kiro
Run with:  python -m pytest test_calculator.py -v
"""
import unittest


# ── Code under test ──────────────────────────────────────────────────────────
class Calculator:
    """Simple calculator with basic arithmetic operations."""

    def add(self, a: float, b: float) -> float:
        return a + b

    def subtract(self, a: float, b: float) -> float:
        return a - b

    def multiply(self, a: float, b: float) -> float:
        return a * b

    def divide(self, a: float, b: float) -> float:
        if b == 0:
            raise ZeroDivisionError("Cannot divide by zero")
        return a / b

    def power(self, base: float, exp: float) -> float:
        return base ** exp

    def modulo(self, a: float, b: float) -> float:
        if b == 0:
            raise ZeroDivisionError("Cannot modulo by zero")
        return a % b


# ── Tests ─────────────────────────────────────────────────────────────────────
class TestCalculatorAdd(unittest.TestCase):
    def setUp(self):
        self.calc = Calculator()

    def test_add_positive(self):    self.assertEqual(self.calc.add(2, 3),    5)
    def test_add_negative(self):    self.assertEqual(self.calc.add(-1, -1), -2)
    def test_add_zero(self):        self.assertEqual(self.calc.add(5, 0),    5)
    def test_add_floats(self):      self.assertAlmostEqual(self.calc.add(0.1, 0.2), 0.3, places=10)


class TestCalculatorSubtract(unittest.TestCase):
    def setUp(self):
        self.calc = Calculator()

    def test_subtract_positive(self): self.assertEqual(self.calc.subtract(10, 3), 7)
    def test_subtract_negative(self): self.assertEqual(self.calc.subtract(-5, -3), -2)
    def test_subtract_zero(self):     self.assertEqual(self.calc.subtract(7,  0), 7)


class TestCalculatorMultiply(unittest.TestCase):
    def setUp(self):
        self.calc = Calculator()

    def test_multiply_positive(self): self.assertEqual(self.calc.multiply(3, 4), 12)
    def test_multiply_negative(self): self.assertEqual(self.calc.multiply(-2, 3), -6)
    def test_multiply_zero(self):     self.assertEqual(self.calc.multiply(99, 0), 0)
    def test_multiply_floats(self):   self.assertAlmostEqual(self.calc.multiply(2.5, 4), 10.0)


class TestCalculatorDivide(unittest.TestCase):
    def setUp(self):
        self.calc = Calculator()

    def test_divide_positive(self):   self.assertEqual(self.calc.divide(10, 2), 5)
    def test_divide_float_result(self): self.assertAlmostEqual(self.calc.divide(7, 2), 3.5)
    def test_divide_by_zero(self):
        with self.assertRaises(ZeroDivisionError):
            self.calc.divide(10, 0)


class TestCalculatorPower(unittest.TestCase):
    def setUp(self):
        self.calc = Calculator()

    def test_power_positive(self): self.assertEqual(self.calc.power(2, 10), 1024)
    def test_power_zero_exp(self): self.assertEqual(self.calc.power(5, 0),    1)
    def test_power_negative(self): self.assertAlmostEqual(self.calc.power(2, -1), 0.5)


if __name__ == "__main__":
    unittest.main(verbosity=2)
''',
    },

    "fibonacci": {
        "keywords": ["fibonacci", "fib", "sequence", "series"],
        "file_ext": "py",
        "subtasks": [
            "Analysing Fibonacci requirements",
            "Choosing algorithm (iterative for O(n) space efficiency)",
            "Implementing fibonacci(n) function",
            "Adding memoized / recursive variant",
            "Adding generator variant for large n",
            "Writing examples & __main__ block",
            "Writing file to workspace",
        ],
        "code": '''\
"""
Fibonacci Implementations — three flavours
Generated by Code Alpha Kiro
"""
from functools import lru_cache
from typing import Iterator


# ── 1. Simple iterative (fastest for single call) ────────────────────────────
def fibonacci(n: int) -> list[int]:
    """Return the first *n* Fibonacci numbers as a list."""
    if n <= 0:
        return []
    if n == 1:
        return [0]
    seq = [0, 1]
    while len(seq) < n:
        seq.append(seq[-1] + seq[-2])
    return seq


# ── 2. Memoised recursive (clean for repeated single-value lookups) ──────────
@lru_cache(maxsize=None)
def fib(n: int) -> int:
    """Return the n-th Fibonacci number (0-indexed)."""
    if n < 0:
        raise ValueError("n must be >= 0")
    if n in (0, 1):
        return n
    return fib(n - 1) + fib(n - 2)


# ── 3. Generator (memory-efficient for very large sequences) ─────────────────
def fib_gen(limit: int) -> Iterator[int]:
    """Yield Fibonacci numbers up to (but not including) *limit*."""
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a + b


# ── Demo ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("First 10 :", fibonacci(10))
    print("fib(20)  :", fib(20))
    print("Under 100:", list(fib_gen(100)))
''',
    },

    "data_model": {
        "keywords": ["data model", "model", "schema", "dataclass", "pydantic", "database", "entity"],
        "file_ext": "py",
        "subtasks": [
            "Analysing data model requirements",
            "Identifying entities and relationships",
            "Defining User model with fields & validators",
            "Defining Post model with FK relationship",
            "Defining Comment model",
            "Adding serialisation / from_dict helpers",
            "Adding example usage block",
            "Writing file to workspace",
        ],
        "code": '''\
"""
Data Models — User / Post / Comment
Generated by Code Alpha Kiro
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional
from uuid import uuid4


def _now() -> datetime:
    return datetime.utcnow()


def _uid() -> str:
    return str(uuid4())[:8]


# ── User ─────────────────────────────────────────────────────────────────────
@dataclass
class User:
    id:         str      = field(default_factory=_uid)
    username:   str      = ""
    email:      str      = ""
    role:       str      = "user"          # user | admin | moderator
    is_active:  bool     = True
    created_at: datetime = field(default_factory=_now)

    def to_dict(self) -> dict:
        return {
            "id": self.id, "username": self.username, "email": self.email,
            "role": self.role, "is_active": self.is_active,
            "created_at": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "User":
        data = dict(data)
        if "created_at" in data and isinstance(data["created_at"], str):
            data["created_at"] = datetime.fromisoformat(data["created_at"])
        return cls(**data)

    def __repr__(self) -> str:
        return f"<User id={self.id} username={self.username!r}>"


# ── Post ──────────────────────────────────────────────────────────────────────
@dataclass
class Post:
    id:         str           = field(default_factory=_uid)
    author_id:  str           = ""
    title:      str           = ""
    body:       str           = ""
    tags:       List[str]     = field(default_factory=list)
    published:  bool          = False
    created_at: datetime      = field(default_factory=_now)
    updated_at: datetime      = field(default_factory=_now)

    def publish(self) -> None:
        self.published  = True
        self.updated_at = _now()

    def to_dict(self) -> dict:
        return {
            "id": self.id, "author_id": self.author_id,
            "title": self.title, "body": self.body,
            "tags": self.tags, "published": self.published,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }


# ── Comment ──────────────────────────────────────────────────────────────────
@dataclass
class Comment:
    id:         str      = field(default_factory=_uid)
    post_id:    str      = ""
    author_id:  str      = ""
    body:       str      = ""
    created_at: datetime = field(default_factory=_now)

    def to_dict(self) -> dict:
        return {
            "id": self.id, "post_id": self.post_id,
            "author_id": self.author_id, "body": self.body,
            "created_at": self.created_at.isoformat(),
        }


# ── Demo ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    alice = User(username="alice", email="alice@example.com", role="admin")
    post  = Post(author_id=alice.id, title="Hello World", body="My first post!", tags=["intro", "general"])
    post.publish()
    comment = Comment(post_id=post.id, author_id=alice.id, body="Great post!")

    print(alice)
    print(post.to_dict())
    print(comment.to_dict())
''',
    },

    "hello_world": {
        "keywords": ["hello", "hello world", "simple", "basic", "starter", "example"],
        "file_ext": "py",
        "subtasks": [
            "Analysing requirements",
            "Creating main function",
            "Adding user input",
            "Writing file to workspace",
        ],
        "code": '''\
"""Hello World — starter program."""


def greet(name: str = "World") -> str:
    return f"Hello, {name}!"


if __name__ == "__main__":
    print(greet())
    name = input("Your name: ").strip()
    if name:
        print(greet(name))
''',
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# PATTERN MATCHING  (score-based, highest wins)
# ─────────────────────────────────────────────────────────────────────────────

def pick_pattern(prompt: str) -> str:
    pl = prompt.lower()
    scores: Dict[str, int] = {}
    for pname, pdata in PATTERNS.items():
        score = 0
        for kw in pdata["keywords"]:
            if kw in pl:
                # longer keyword = more specific = higher weight
                score += len(kw.split())
        scores[pname] = score

    best = max(scores, key=lambda k: scores[k])
    # if nothing matched at all, default to hello_world
    return best if scores[best] > 0 else "hello_world"


# ─────────────────────────────────────────────────────────────────────────────
# TASK STORE
# ─────────────────────────────────────────────────────────────────────────────

_store: Dict[str, dict] = {}


def _make_task(prompt: str, repo_path: str) -> dict:
    tid     = "task_" + uuid.uuid4().hex[:8]
    pname   = pick_pattern(prompt)
    pdata   = PATTERNS[pname]
    ext     = pdata["file_ext"]
    fname   = f"{tid}_{pname}.{ext}"
    fpath   = str(Path(repo_path).resolve() / fname)

    sub_tasks = [
        {"id": i, "name": name, "status": "pending", "detail": ""}
        for i, name in enumerate(pdata["subtasks"])
    ]

    return {
        "task_id":        tid,
        "prompt":         prompt,
        "status":         "pending",
        "pattern":        pname,
        "file_ext":       ext,
        "file_name":      fname,
        "file_path":      fpath,
        "sub_tasks":      sub_tasks,
        "generated_code": None,
        "logs":           [f"✓ Received: {prompt}"],
        "code_template":  pdata["code"],
        "repo_path":      repo_path,
    }


# ─────────────────────────────────────────────────────────────────────────────
# SYNCHRONOUS EXECUTION  (runs inside SSE stream so UI sees every step)
# ─────────────────────────────────────────────────────────────────────────────

async def _run_task(task: dict):
    """Advance every sub-task one at a time; update store in place."""
    task["status"] = "running"

    for st in task["sub_tasks"]:
        st["status"] = "running"
        task["logs"].append(f"▶ {st['name']}")
        await asyncio.sleep(0.4)          # simulate work
        st["status"] = "complete"
        st["detail"] = "done"
        task["logs"].append(f"✓ {st['name']}")

    # Write file
    try:
        code = task["code_template"]
        Path(task["file_path"]).write_text(code, encoding="utf-8")
        task["generated_code"] = code
        task["logs"].append(f"✓ File written → {task['file_name']}")
    except Exception as exc:
        task["logs"].append(f"✗ File write failed: {exc}")

    task["status"] = "complete"


# ─────────────────────────────────────────────────────────────────────────────
# ENDPOINTS
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {"status": "healthy", "version": "4.0.0", "ts": datetime.utcnow().isoformat()}


@app.post("/tasks", response_model=TaskOut)
async def create_task(body: TaskCreate):
    task = _make_task(body.prompt, body.repo_path)
    _store[task["task_id"]] = task
    # Kick off real execution in background
    asyncio.ensure_future(_run_task(task))
    return _task_out(task)


@app.get("/tasks/{task_id}", response_model=TaskOut)
async def get_task(task_id: str):
    task = _store.get(task_id)
    if not task:
        raise HTTPException(404, "Task not found")
    return _task_out(task)


@app.get("/tasks/{task_id}/stream")
async def stream_task(task_id: str):
    """SSE stream — pushes a JSON snapshot after every sub-task update."""
    task = _store.get(task_id)
    if not task:
        raise HTTPException(404, "Task not found")

    async def generator():
        while True:
            payload = json.dumps(_task_out(task).dict())
            yield f"data: {payload}\n\n"
            if task["status"] in ("complete", "error"):
                break
            await asyncio.sleep(0.2)

    return StreamingResponse(generator(), media_type="text/event-stream",
                             headers={"Cache-Control": "no-cache",
                                      "X-Accel-Buffering": "no"})


@app.put("/tasks/{task_id}/code")
async def update_code(task_id: str, body: dict):
    """Allow the user to save edited code back to the file."""
    task = _store.get(task_id)
    if not task:
        raise HTTPException(404, "Task not found")
    new_code = body.get("code", "")
    task["generated_code"] = new_code
    try:
        Path(task["file_path"]).write_text(new_code, encoding="utf-8")
    except Exception as exc:
        raise HTTPException(500, f"File write failed: {exc}")
    return {"saved": True, "file_path": task["file_path"]}


@app.get("/tasks")
async def list_tasks():
    return [_task_out(t) for t in _store.values()]


def _task_out(task: dict) -> TaskOut:
    return TaskOut(
        task_id        = task["task_id"],
        prompt         = task["prompt"],
        status         = task["status"],
        pattern        = task["pattern"],
        file_ext       = task["file_ext"],
        file_name      = task["file_name"],
        file_path      = task["file_path"],
        sub_tasks      = [SubTask(**st) for st in task["sub_tasks"]],
        generated_code = task["generated_code"],
        logs           = task["logs"],
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, loop="asyncio")
