import React,{useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Canvas,useFrame} from '@react-three/fiber'
import {OrbitControls,Float,Stars} from '@react-three/drei'
import * as THREE from 'three'
import {Send,LayoutDashboard,MessageSquare,Bot,Code2,FileText,FlaskConical,Brain,BarChart3,Settings,ShieldCheck,CreditCard,Search,Plus,Play,Upload,Terminal,ChevronRight,Zap,Database,Activity,Layers3} from 'lucide-react'
import './style.css'

const pages=[
['Dashboard',LayoutDashboard],['AI Chat',MessageSquare],['Agents',Bot],['Coding Agent',Code2],
['RAG Studio',FileText],['Code Lab',Terminal],['Prompt Lab',FlaskConical],['Model Arena',Layers3],
['Memory',Brain],['Analytics',BarChart3],['Billing',CreditCard],['Settings',Settings],['Admin',ShieldCheck]
]
function Orb(){const ref=React.useRef();useFrame((s)=>{ref.current.rotation.x=s.clock.elapsedTime*.12;ref.current.rotation.y=s.clock.elapsedTime*.18});return <Float speed={1.4} rotationIntensity={.5} floatIntensity={1}><mesh ref={ref}><icosahedronGeometry args={[2.2,3]}/><meshStandardMaterial color="#7c3aed" wireframe emissive="#22d3ee" emissiveIntensity={2}/></mesh></Float>}
function Scene(){return <div className="scene"><Canvas camera={{position:[0,0,8]}}><ambientLight intensity={.4}/><pointLight position={[4,4,5]} intensity={40} color="#8b5cf6"/><pointLight position={[-4,-2,3]} intensity={25} color="#06b6d4"/><Stars radius={70} depth={30} count={1200} factor={2}/><Orb/><OrbitControls enableZoom={false} autoRotate autoRotateSpeed={.25}/></Canvas></div>}
const Metric=({label,value,delta})=><div className="metric"><span>{label}</span><b>{value}</b><small>↗ {delta}</small></div>
function Dashboard(){return <><header><div><span className="eyebrow">DEVMIND AI PRO</span><h1>Build intelligence.<br/><em>Ship faster.</em></h1><p>One workspace for LLM apps, agents, RAG and autonomous coding.</p></div><button className="primary"><Zap size={16}/> New Project</button></header><div className="metrics"><Metric label="Tokens this month" value="2.48M" delta="18.4%"/><Metric label="Agent runs" value="1,284" delta="31.2%"/><Metric label="Knowledge chunks" value="18,420" delta="12.8%"/><Metric label="Avg latency" value="1.42s" delta="8.1%"/></div><section className="grid2"><div className="card hero-card"><div><span className="pill">LIVE AGENT</span><h2>Autonomous Coding Agent</h2><p>Plan → code → test → fix → explain. Your AI engineering teammate.</p><button className="ghost">Open workspace <ChevronRight size={16}/></button></div><div className="mini-orb">AI</div></div><div className="card"><div className="card-title"><span>Activity</span><Activity size={17}/></div><div className="bars">{[38,62,48,80,56,91,73,67,88,55,94,72].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div><div className="legend"><b>86.4K</b> requests · last 24 hours</div></div></section><section className="grid3"><div className="card"><Database/><h3>RAG Studio</h3><p>18,420 indexed chunks across 64 documents.</p></div><div className="card"><Bot/><h3>Agent Fleet</h3><p>7 agents active with 42 tool calls today.</p></div><div className="card"><Code2/><h3>Code Workspace</h3><p>12 projects, 184 files generated this week.</p></div></section></>}
function Chat(){const [msgs,setMsgs]=useState([{r:'ai',t:'Welcome to DevMind. I can reason, search your knowledge base and write code.'}]);const [v,setV]=useState('');return <><PageHead title="AI Chat" sub="Context-aware conversations with streaming responses."/><div className="chat card"><div className="chat-top"><span className="status"/><b>DevMind · Architect</b><span className="muted">GPT / Llama compatible</span></div><div className="messages">{msgs.map((m,i)=><div className={'bubble '+m.r} key={i}>{m.t}</div>)}</div><div className="composer"><Plus/><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&v){setMsgs([...msgs,{r:'user',t:v},{r:'ai',t:'I would execute this request through the configured model, tools and memory.'}]);setV('')}}} placeholder="Ask anything…"/><button className="send" onClick={()=>v&&(setMsgs([...msgs,{r:'user',t:v},{r:'ai',t:'Request received. Streaming model response…'}]),setV(''))}><Send/></button></div></div></>}
function Generic({name}){let data={Agents:['Multi-tool autonomous agents','Design, run and inspect agent graphs.'],['Coding Agent']:['Autonomous Coding','Generate files, run tests and iterate safely.'],['RAG Studio']:['Knowledge Intelligence','Ingest, chunk, retrieve and rerank your private knowledge.'],['Code Lab']:['Code Laboratory','A premium IDE surface for generated and reviewed code.'],['Prompt Lab']:['Prompt Engineering','Version prompts, evaluate outputs and compare runs.'],['Model Arena']:['Model Arena','Compare models, latency, cost and quality side-by-side.'],Memory:['Long-Term Memory','Control what DevMind remembers and why.'],Analytics:['Analytics','Token, latency, quality and agent observability.'],Billing:['Billing & Usage','Usage meters, plans and invoices.'],Settings:['Settings','Workspace, security and model preferences.'],Admin:['Admin Control Center','Users, audit logs, limits and system health.']}[name]||[name,'Workspace'];return <><PageHead title={data[0]} sub={data[1]}/><div className="workspace-grid"><div className="card tall"><div className="card-title"><b>Workspace</b><span className="pill">PRO</span></div><div className="feature-list">{['Overview','Configuration','Runs','Evaluation','Logs'].map((x,i)=><div className="feature" key={x}><span>{i+1}</span><div><b>{x}</b><p>Production-ready controls and detailed observability.</p></div><ChevronRight/></div>)}</div></div><div className="card tall"><div className="terminal"><span>● ● ●</span><pre>{`$ devmind ${name.toLowerCase().replaceAll(' ','-')}
> initializing workspace...
> loading tools
> connecting model router
> ready

STATUS: OPERATIONAL`}</pre></div><button className="primary wide"><Play size={16}/> Run workspace</button></div></div></>}
function PageHead({title,sub}){return <header className="page-head"><div><span className="eyebrow">WORKSPACE</span><h1>{title}</h1><p>{sub}</p></div><button className="ghost"><Search size={16}/> Search</button></header>}
function App(){const [page,setPage]=useState('Dashboard');return <div><Scene/><aside><div className="brand"><div className="logo">D</div><div><b>DEVMIND</b><small>AI PLATFORM</small></div></div><div className="nav">{pages.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={17}/>{n}</button>)}</div><div className="profile"><div className="avatar">IA</div><div><b>Developer</b><small>Pro Workspace</small></div><ChevronRight size={15}/></div></aside><main>{page==='Dashboard'?<Dashboard/>:page==='AI Chat'?<Chat/>:<Generic name={page}/>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>)
