import React,{useEffect,useState}from'react';import{NavLink,Route,Routes,useNavigate}from'react-router-dom';import{Activity,Archive,ArrowUpRight,Bot,Brain,ChevronDown,Code2,CreditCard,Database,FileText,FlaskConical,LayoutDashboard,Menu,MessageSquare,Plus,Search,Settings,ShieldCheck,SlidersHorizontal,Sparkles,Terminal,Upload,UserRound,ScanEye}from'lucide-react';import{api,upload}from'./api';

const navGroups=[
  {title:'CORE',items:[['/','Overview',LayoutDashboard],['/chat','AI Chat',MessageSquare]]},
  {title:'BUILD',items:[['/agents','Agent Studio',Bot],['/coding','Coding Agent',Code2]]},
  {title:'KNOWLEDGE',items:[['/rag','RAG Studio',FileText],['/vision','Vision Lab',ScanEye]]},
  {title:'EVALUATE',items:[['/prompts','Prompt Lab',FlaskConical],['/models','Model Arena',SlidersHorizontal]]},
  {title:'WORKSPACE',items:[['/memory','Memory',Brain]]},
  {title:'ACCOUNT',items:[['/billing','Billing',CreditCard]]},
  {title:'ADMIN',items:[['/admin','Admin',ShieldCheck],['/settings','Settings',Settings]]}
] as const;

function Shell(){const[n,setN]=useState(false);return <div className="app"><aside className={n?'open':''}><div className="brand"><div className="brandmark"><Sparkles size={17}/></div><div><b>DEVMIND</b><small>AI WORKSPACE</small></div></div><NavLink to="/chat" className="new"><Plus size={16}/> New conversation</NavLink><div className="nav-groups">{navGroups.map(group=><div className="nav-group" key={group.title}><div className="nav-title">{group.title}</div><nav>{group.items.map(([to,label,I])=><NavLink key={to} to={to} end={to==='/' }><I size={17}/><span>{label}</span></NavLink>)}</nav></div>)}</div><div className="side-bottom"><div className="usage-mini"><span>Daily usage</span><b>8 / 20</b><i><em/></i></div><div className="account"><div className="avatar">IA</div><div><b>Developer</b><small>Free workspace</small></div><Settings size={15}/></div></div></aside><main><div className="mobilebar"><button onClick={()=>setN(!n)}><Menu/></button><b>DEVMIND</b></div><Routes><Route path="/" element={<Overview/>}/><Route path="/chat" element={<Chat/>}/><Route path="/agents" element={<Agents/>}/><Route path="/coding" element={<Coding/>}/><Route path="/rag" element={<Rag/>}/><Route path="/vision" element={<VisionPage/>}/><Route path="/prompts" element={<Prompts/>}/><Route path="/models" element={<Models/>}/><Route path="/memory" element={<Memory/>}/><Route path="/billing" element={<Billing/>}/><Route path="/admin" element={<Admin/>}/><Route path="/settings" element={<SettingsPage/>}/></Routes></main></div>}

function Top({eyebrow='WORKSPACE',title,sub,action}:{eyebrow?:string,title:string,sub?:string,action?:React.ReactNode}){return <header className="top"><div><span>{eyebrow}</span><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{action}</header>}
function Card({children,className='' }:{children:React.ReactNode,className?:string}){return <section className={'card '+className}>{children}</section>}
function Overview(){const[s,setS]=useState<any>({users:0,conversations:0,messages:0,dau:37,latency_ms:1280,cost_today:12.84});useEffect(()=>{api('/admin/stats').then(setS).catch(()=>{})},[]);return <><Top eyebrow="CONTROL CENTER" title="Good evening, Imtiaz." sub="Your AI workspace is ready. Monitor intelligence, build agents, and ship faster." action={<button className="primary"><Plus size={16}/> New project</button>}/><div className="stats"><Stat label="Messages" value={s.messages||'—'} trend="+18.2%"/><Stat label="Active users" value={s.dau} trend="+9.4%"/><Stat label="Avg. latency" value={(s.latency_ms/1000).toFixed(2)+'s'} trend="-12.8%"/><Stat label="AI cost today" value={'$'+s.cost_today} trend="+4.2%"/></div><div className="cols"><Card className="chart-card"><div className="section-head"><div><b>Usage intelligence</b><small>Requests across the last 14 days</small></div><button className="ghost">14 days <ChevronDown size={14}/></button></div><div className="chart"><div className="gridlines">{[1,2,3,4].map(x=><i key={x}/>)}</div><svg viewBox="0 0 700 220" preserveAspectRatio="none"><defs><linearGradient id="g"><stop stopColor="#0e8a6d"/><stop offset="1" stopColor="#7c3aed"/></linearGradient></defs><path d="M0 185 C50 170 65 130 110 145 S180 80 220 120 S290 100 330 130 S390 60 440 95 S500 140 545 92 S620 50 700 65" fill="none" stroke="url(#g)" strokeWidth="4"/></svg></div><div className="chart-foot"><span><i className="dot teal"/> Requests <b>86.4K</b></span><span><i className="dot purple"/> Tokens <b>2.48M</b></span></div></Card><Card><div className="section-head"><div><b>Model routing</b><small>Quality / speed mix</small></div><ArrowUpRight size={16}/></div>{[['Llama 3.3 70B','54%','Fast'],['Llama 4 Scout','28%','Vision'],['DeepSeek R1','18%','Reasoning']].map((x,i)=><div className="modelrow" key={x[0]}><div className="modelicon">{i===0?<Sparkles/>:i===1?<ScanEye/>:<Brain/>}</div><div><b>{x[0]}</b><small>{x[2]}</small></div><strong>{x[1]}</strong></div>)}</Card></div><div className="three"><Quick icon={<Bot/>} title="Agent fleet" text="7 workflows ready to run" link="/agents"/><Quick icon={<Database/>} title="Knowledge base" text="64 documents · 18.4K chunks" link="/rag"/><Quick icon={<Code2/>} title="Coding workspace" text="12 projects · clean tree" link="/coding"/></div></>}
function Stat({label,value,trend}:{label:string,value:any,trend:string}){return <div className="stat"><small>{label}</small><b>{value}</b><em>{trend}</em></div>}
function Quick({icon,title,text,link}:{icon:any,title:string,text:string,link:string}){return <NavLink className="quick card" to={link}>{icon}<b>{title}</b><span>{text}</span><ArrowUpRight size={15}/></NavLink>}

function Chat(){const[msg,setMsg]=useState<any[]>([]),[v,setV]=useState(''),[rag,setRag]=useState(false),[model,setModel]=useState('llama-3.3-70b-versatile'),send=async()=>{if(!v.trim())return;const q=v;setV('');setMsg(x=>[...x,{role:'user',content:q},{role:'assistant',content:'Thinking…'}]);try{const r=await api('/chat',{method:'POST',body:JSON.stringify({message:q,model,use_rag:rag})});setMsg(x=>[...x.slice(0,-1),{role:'assistant',content:r.answer}])}catch(e:any){setMsg(x=>[...x.slice(0,-1),{role:'assistant',content:'⚠ '+e.message}])}};return <div className="chat-page"><div className="chat-head"><div><span className="live"/> DevMind <small>AI Architect</small></div><select value={model} onChange={e=>setModel(e.target.value)}><option value="llama-3.3-70b-versatile">Llama 3.3 70B · Balanced</option><option value="llama-3.1-8b-instant">Llama 3.1 8B · Fast</option></select></div><div className="messages">{msg.length===0?<div className="welcome"><div className="welcome-icon"><Sparkles/></div><h2>What are you building today?</h2><p>Ask DevMind to reason, code, analyze documents, or orchestrate tools.</p><div className="suggestions"><button onClick={()=>setV('Design a production RAG architecture')}>Design a RAG architecture</button><button onClick={()=>setV('Build a FastAPI authentication module')}>Build an auth module</button><button onClick={()=>setV('Review my project architecture')}>Review architecture</button></div></div>:msg.map((m,i)=><div className={'message '+m.role} key={i}><div className="msgavatar">{m.role==='user'?'IA':'✦'}</div><div><small>{m.role==='user'?'You':'DevMind'}</small><div className="markdown">{m.content}</div></div></div>)}</div><div className="composer"><button title="Attach"><Upload size={18}/></button><button className={rag?'active':''} onClick={()=>setRag(!rag)} title="Use RAG"><Database size={18}/></button><textarea value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message DevMind…"/><button className="send" onClick={send}><ArrowUpRight size={19}/></button><small>Enter to send · Shift+Enter for newline</small></div></div>}

function Agents(){const[t,setT]=useState('Analyze this repository and propose a clean production architecture.'),[out,setOut]=useState('');return <><Top title="Agent Studio" sub="Build tool-using autonomous workflows with inspectable execution." action={<button className="primary"><Plus size={16}/> New agent</button>}/><div className="agent-grid"><Card><div className="agent-hero"><div className="orb"><Bot/></div><div><span className="pill">REACT LOOP</span><h2>Engineering Agent</h2><p>Plan → tools → observe → revise → final.</p></div></div><label>Task</label><textarea className="biginput" value={t} onChange={e=>setT(e.target.value)}/><div className="toolchips"><span>▣ File Search</span><span>⌁ Calculator</span><span>⌘ Memory</span><span>◈ RAG</span></div><button className="primary wide" onClick={async()=>{setOut('Running…');try{const r=await api('/agent/run',{method:'POST',body:JSON.stringify({task:t,tools:['calculator']})});setOut(r.result)}catch(e:any){setOut(e.message)}}}><Sparkles size={16}/> Run agent</button></Card><Card><div className="section-head"><div><b>Execution trace</b><small>Live reasoning/tool events</small></div><span className="pill">SAFE MODE</span></div><div className="trace">{['Planner','Tool router','Calculator / File tools','Verifier','Final response'].map((x,i)=><div key={x} className={i===4?'done':''}><i>{i+1}</i><span><b>{x}</b><small>{i<3?'Completed':'Waiting for run'}</small></span></div>)}</div><pre className="output">{out||'> Awaiting an agent run…'}</pre></Card></div></>}

function Coding(){const[task,setTask]=useState('Create a FastAPI CRUD API for students with tests.'),[out,setOut]=useState('');return <><Top title="Coding Agent" sub="Natural language → plan → changes → review. Execution stays sandboxed." action={<span className="safe"><ShieldCheck size={15}/> Sandbox protected</span>}/><div className="coding"><Card className="code-chat"><div className="section-head"><b>Task</b><span className="pill">AUTONOMOUS</span></div><textarea className="biginput" value={task} onChange={e=>setTask(e.target.value)}/><div className="checklist">{['Inspect workspace','Create implementation plan','Generate multi-file patch','Run tests in sandbox','Show diff for approval'].map((x,i)=><div key={x}><span>{i+1}</span>{x}</div>)}</div><button className="primary wide" onClick={async()=>{setOut('Generating plan…');try{const r=await api('/agent/run',{method:'POST',body:JSON.stringify({task,tools:['calculator']})});setOut(r.result)}catch(e:any){setOut(e.message)}}}><Code2 size={16}/> Generate changes</button></Card><Card className="editor"><div className="editorbar"><span>workspace</span><b>student_api.py</b><span>main · clean</span></div><pre><code>{out||`from fastapi import FastAPI\n\napp = FastAPI(title="Student API")\n\n@app.get("/health")\ndef health():\n    return {"status": "ok"}\n\n# Agent changes appear here\n# Review before applying.`}</code></pre><div className="diff"><span>+ Proposed changes will appear in a reviewable diff.</span></div></Card></div></>}

function Rag(){const[file,setFile]=useState<File|null>(null),[docs,setDocs]=useState<any[]>([]),[q,setQ]=useState(''),[res,setRes]=useState<any[]>([]);useEffect(()=>{api('/rag/documents').then(setDocs).catch(()=>{})},[]);return <><Top title="RAG Studio" sub="Upload knowledge, index it, retrieve relevant evidence and cite sources." action={<label className="primary"><Upload size={16}/> Upload<input hidden type="file" accept=".pdf,.txt,.md" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}/><div className="raggrid"><Card><div className="drop"><FileText size={30}/><b>{file?file.name:'Drop documents here'}</b><span>PDF, TXT or Markdown · scoped to your workspace</span>{file&&<button className="primary" onClick={async()=>{await upload('/rag/upload',file);setDocs(await api('/rag/documents'));}}>Index document</button>}</div><h3>Indexed documents</h3>{docs.map(d=><div className="doc" key={d.id}><FileText/><div><b>{d.name}</b><small>{d.status} · private</small></div><span>Indexed</span></div>)}</Card><Card><div className="section-head"><div><b>Retriever</b><small>Hybrid-ready search surface</small></div><Database/></div><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your knowledge…"/><button onClick={async()=>setRes(await api('/rag/search?q='+encodeURIComponent(q)))}>Search</button></div>{res.map((r,i)=><div className="source" key={i}><span>p.{r.page}</span><p>{r.text}</p></div>)}</Card></div></>}

function VisionPage(){const[file,setFile]=useState<File|null>(null),[q,setQ]=useState('Describe this image and extract important structured information.'),[out,setOut]=useState('');return <><Top title="Vision Lab" sub="Ask questions about images or extract structured information."/><div className="visiongrid"><Card><label className="uploadbox"><Upload size={30}/><b>{file?.name||'Choose an image'}</b><small>PNG, JPEG or WebP</small><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><textarea className="biginput" value={q} onChange={e=>setQ(e.target.value)}/><button className="primary wide" disabled={!file} onClick={async()=>{if(!file)return;const fd=new FormData();fd.append('file',file);fd.append('question',q);const token=localStorage.getItem('token');const r=await fetch('http://localhost:8000/api/vision/analyze',{method:'POST',body:fd,headers:token?{Authorization:`Bearer ${token}`}:{}});const x=await r.json();setOut(x.answer||x.detail)}}><Sparkles size={16}/> Analyze image</button></Card><Card><span className="eyebrow">MODEL OUTPUT</span><pre className="output visionout">{out||'Your multimodal response will appear here.'}</pre></Card></div></>}

function Prompts(){return <><Top title="Prompt Lab" sub="Version, test and compare prompts before production."/><div className="promptgrid"><Card><div className="section-head"><b>System prompt</b><span className="pill">v12</span></div><textarea className="promptbox" defaultValue="You are DevMind, a senior software engineer. Be precise, practical, and explain trade-offs."/><label>Variables</label><div className="vars"><span>{'{language}'}</span><span>{'{audience}'}</span><span>{'{tone}'}</span></div><button className="primary">Run evaluation</button></Card><Card><div className="section-head"><b>Evaluation</b><span className="pill">8 test cases</span></div>{['Accuracy','Instruction following','Groundedness','Latency'].map((x,i)=><div className="score" key={x}><span>{x}</span><b>{[94,91,88,97][i]}%</b><i><em style={{width:[94,91,88,97][i]+'%'}}/></i></div>)}</Card></div></>}

function Models(){return <><Top title="Model Arena" sub="Choose by speed, reasoning depth, vision capability and cost."/><div className="modelcards">{[['Llama 3.3 70B','Balanced','Best default','green'],['Llama 3.1 8B','Fast','Low latency','blue'],['Llama 4 Scout','Vision','Multimodal','purple']].map(x=><Card key={x[0]}><span className={'model-badge '+x[3]}>{x[1]}</span><h2>{x[0]}</h2><p>{x[2]}</p><div className="spec"><span>Latency <b>~1.2s</b></span><span>Cost <b>Low</b></span><span>Context <b>Large</b></span></div><button className="ghost wide">Use model</button></Card>)}</div></>}

function Memory(){const[m,setM]=useState<any[]>([]),[k,setK]=useState(''),[v,setV]=useState('');const load=()=>{api('/memory').then(setM).catch(()=>{})};useEffect(()=>{load()},[]);return <><Top title="Memory" sub="Give the assistant durable, user-controlled context." action={<span className="safe"><Brain size={15}/> Memory enabled</span>}/><div className="memorygrid"><Card><h3>Add a memory</h3><input className="field" placeholder="Key e.g. role" value={k} onChange={e=>setK(e.target.value)}/><textarea className="biginput" placeholder="Value" value={v} onChange={e=>setV(e.target.value)}/><button className="primary" onClick={async()=>{await api('/memory',{method:'POST',body:JSON.stringify({key:k,value:v})});setK('');setV('');load()}}>Save memory</button></Card><Card><div className="section-head"><b>Stored facts</b><small>Only what you control</small></div>{m.length?m.map(x=><div className="memory" key={x.id}><div><b>{x.key}</b><p>{x.value}</p></div><button onClick={async()=>{await api('/memory/'+x.id,{method:'DELETE'});load()}}>Delete</button></div>):<p>No memories yet.</p>}</Card></div></>}

function Billing(){const plans=[['Free','$0','20 messages/day'],['Plus','$19','1,000 messages/day'],['Pro','$49','10,000 messages/day']];return <><Top title="Plans & Billing" sub="Scale from experimentation to production workloads."/><div className="pricing">{plans.map((p,i)=><Card key={p[0]} className={i===1?'featured':''}><span className="pill">{i===1?'POPULAR':'PLAN'}</span><h2>{p[0]}</h2><b className="price">{p[1]}<small>/mo</small></b><p>{p[2]}</p><ul><li>Streaming responses</li><li>Conversation history</li><li>Developer workspace</li><li>{i?'Advanced models':'Standard model'}</li></ul><button className={i===1?'primary':'ghost'}>{i?'Upgrade':'Current plan'}</button></Card>)}</div></>}

function Admin(){return <><Top eyebrow="INTERNAL" title="Admin & Analytics" sub="Operational visibility across users, models and costs."/><div className="stats"><Stat label="Users" value="1,284" trend="+12.4%"/><Stat label="DAU" value="372" trend="+8.1%"/><Stat label="Messages/day" value="18.4K" trend="+22.7%"/><Stat label="Token cost/day" value="$42.18" trend="-6.3%"/></div><div className="admin-grid"><Card><div className="section-head"><b>User management</b><button className="ghost"><Search size={14}/> Search</button></div>{['Ayesha Khan','Imtiaz Ali','Hamza Ahmed','Sara Malik'].map((x,i)=><div className="userrow" key={x}><div className="avatar">{x.split(' ').map(y=>y[0]).join('')}</div><div><b>{x}</b><small>{i%2?'Pro':'Free'} · Active</small></div><span>{[284,193,91,77][i]} messages</span><button>•••</button></div>)}</Card><Card><div className="section-head"><b>System health</b><span className="safe"><Activity size={14}/> All systems normal</span></div>{['Groq gateway','PostgreSQL','Redis','RAG workers','Agent sandbox'].map(x=><div className="health" key={x}><span className="live"/><b>{x}</b><small>Operational</small></div>)}</Card></div></>}

function SettingsPage(){return <><Top title="Settings" sub="Personalize the workspace, model behavior and data controls."/><div className="settings"><Card><h3>General</h3><div className="setting"><div><b>Theme</b><small>Choose how DevMind looks.</small></div><select><option>System</option><option>Light</option><option>Dark</option></select></div><div className="setting"><div><b>Font size</b><small>Comfortable reading size.</small></div><select><option>Default</option><option>Large</option></select></div><div className="setting"><div><b>Streaming</b><small>Show model output token-by-token.</small></div><input type="checkbox" defaultChecked/></div></Card><Card><h3>Personalization</h3><label>What should DevMind know about you?</label><textarea className="biginput" placeholder="Your role, goals, technical background…"/><label>How should it respond?</label><textarea className="biginput" placeholder="Concise, detailed, Urdu/Hinglish, code-first…"/><button className="primary">Save preferences</button></Card></div></>}

export default Shell
